# Set theme
#remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- CODE_OF_CONDUCT.md
- LICENSE
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 5
paginate_path: projects/page:num


# 4. Jekyll settings
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Amsterdam # Timezone for blog posts and alike



# Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
url: 'https://cyber-analytics.nl/'
baseurl: ''
title: 'Cyber Analytics Lab'
description: 'TU Delft'
permalink: pretty
logo: "/assets/TUD.png"
logo2: "/assets/logos/logo-text.svg"
favicon: "/assets/logos/logo.png"
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# Header nav
navigation_header:
- title: Home
  url: /
- title: People
  url: /people/
- title: Projects
  url: /projects/
- title: Publications
  url: /publications/
- title: Contact
  url: /contact/


# Footer nav
navigation_footer:
- title: github
  text: Created by CAL 
  url: "https://github.com/tudelft-cda-lab/"
- title: globe
  text: Powered by GitHub Pages
  url: "https://pages.github.com/themes/"

# Collections
collections:
  posts:
    title: Research projects
    output: true
    feature_image: "https://picsum.photos/2560/600?image=866"
    feature_text: |
      # Research Projects
  papers:
    title: Publication list
    output: false
    feature_image: "https://picsum.photos/2560/600?image=866"
    feature_text: |
      # Recent Publications
  people:
    title: People
    output: true
    feature_image: "https://picsum.photos/2560/600?image=866"
    feature_text: |
      # People
# ---------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------
# Update this collection for adding/removing roles
roles:
- r: leader
  name: Lab head
- r: postdoc
  name: Postdoctoral Researchers
- r: phd
  name: PhD Candidates
- r: msc
  name: MSc. students
- r: external
  name: External collaborators
- r: alumni
  name: Past members


# ---------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------

# Postal address
address: Van Mourik Broekmanweg 6, 2628 XE Delft

# ---------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------


# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
